### ISSUE TITLE
Extension not working with x64 agent on vsts on premises 

### ISSUE THREAD

**Issue by 0xahs** [qetza/replacetokens-action#9]
Facing this:
A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

**Comment by qetza** [comment]
Hi @AhmadHassanSahi,
Thanks for reporting the issue. As for the Azure Pipeline task I'm running test on this GitHub Action on linux, macos and windows without any issues.

As the action requires node 20 to run can you check that your runner is at least in version `2.308.0`?

**Comment by 0xahs** [comment]
Hi @qetza Please see below my agent system capabilities
![Agent](https://github.com/qetza/replacetokens-action/assets/38754480/9302bc3e-b767-4033-ac70-5a292a9845f9)

**Comment by qetza** [comment]
Hi @AhmadHassanSahi, I'm closing the issue as it's related to the Azure Pipelines task.
